# ======================================================== #
# Example Configuration file for the training of the model #
# ======================================================== #


# ======================================================== #

# Cmd line arguments for run modes (-p, -t, -e, -pr)
# mode: 'prepare'
# mode: 'train'
# mode: 'evaluate'
# mode: 'predict'

model:
  name: 'ResidualComplexNN'
  model_builder: True
  input_dim: 6
  output_dim: 1
  num_layers: 3
  hidden_dim: 64
  dropout: 0.1
  use_residual: True
  use_complex: True
  use_normalisation: True
  use_batch_norm: True
  use_skip_connection: True
  use_layer_norm: True

#============#
# Data Block #
#============#
# Path to the data
data:
  signal_path: /scratch4/levans/tth-network/Datasets/basic/signal2.h5
  background_path: /scratch4/levans/tth-network/Datasets/basic/ttbarBackground2.h5
  plot_inputs: True
  save_graph_data: False
  path_to_save_graph: /path/to/save   # make dir if does not exist!
  use_saved_graph_data: False
  train_ratio: 0.8
  value_threshold: 1e-6


#===============#
# Network Block #
#===============#
Network_type:
  - FFNN


#===============#
# Feature Block #
#===============#
features: # example
  - HT_all
  - H0_all
  - dRbb_avg_Sort4
  - nJets
  - Aplanarity_jets
  - Centrality_all
  - dRlj_MindR
  - mu_pt

#===================#
# Preparation Block #
#===================#
# Preparation: Coming soon!
  - feature_scaling: True
  - feature_normalisation: True
  - feature_standardisation: True
  - feature_maker: True
    - feature_maker_type: '4-vectors'
    - feature_maker_type: 'decay-angles'
    - feature_maker_type: 'colour-flows'


#================#
# Training Block #
#================#
training:
  num_epochs: 20
  learning_rate: 0.00001
  weight_decay: 0.001
  batch_size: 100
  patience: 7
  early_stopping: True
  use_scheduler: False
  factor: 0.5
  initialise_weights: True
  balance_classes: True
  criterion: 'BCELoss'
  use_cosine_burnin: True
  save_frequency: 1
  save_plots: False
  k_fold_cross_validation:
   k: 5
   shuffle: True
   stratified: True
   random_state: 42
   save_model: False
   model_save_path: 'models/'
   save_frequency: 1
   save_plots: False

#===================#
# Evaluataion Block #
#===================#
evaluation:
  use_saved_model: False
  saved_model_path: /scratch4/levans/tth-network/models/outputs/model.pt
