# pyproject.toml generic file
[tool.black]
line-length = 88
target-version = ['py39']
exclude = '''
/(
    \.git
  | \.venv
  | env
  | venv
  | \.mypy_cache
  | \.pytest_cache
  | \.tox
  | \.eggs
  | \.egg-info
  | build
  | dist
)/
'''
