# ======================================================== #
# Example Configuration file for the training of the model #
# ======================================================== #


# Name of the model to use and the input dimension
model:
  name: 'TransformerClassifier1'

# Path to the data
data:
  signal_path: /scratch4/levans/tth-network/Datasets/full/10_03_24/ttH/ttH_AFII.h5
  background_path: /scratch4/levans/tth-network/Datasets/full/10_03_24/ttbb/ttbb_AFII.h5
  train_ratio: 0.8
  value_threshold: 1e-6
  plot_inputs: False



Network_type:
  - FFNN

# Example features to be used for training the model

features:
  - jet_pt_1
  - jet_pt_2
  - jet_pt_3
  - jet_pt_4
  - jet_pt_5
  - jet_pt_6
  - jet_pt_7
  - jet_pt_8
  - jet_pt_9
  - jet_pt_10
  - dRbb_avg_Sort4
  - HT_all
  - met_met
  - mwt_mwt
  - H0_all
  - H1_all
  - H2_jets
  - dRlj_MindR
  - dRlepbb_MindR_70
  - Centrality_all
  - dEtabb_MaxdEta_70
  - L2_Reco_higgs_pt
  #- L2_Class_ttH_discriminant


# Hyperparameters for training the model
training:
  num_epochs: 25
  learning_rate: 0.00001
  weight_decay: 0.001
  batch_size: 128 # bug when using higher batch size due to mismatch with positional encoding (fix this)
  patience: 7
  early_stopping: True
  use_scheduler: False
  factor: 0.5
  initialise_weights: True
  balance_classes: True
  criterion: 'BCELoss'
  use_cosine_burnin: True
  lr_init: 1e-9
  lr_max: 1e-4
  lr_final: 1e-5
  burn_in: 5
  ramp_up: 10
  plateau: 15
  ramp_down: 17


evaluation:
  use_saved_model: False
  saved_model_path: /scratch4/levans/tth-network/models/outputs/model.pt