# ======================================================== #
# Example Configuration file for the training of the model #
# ======================================================== #

# mode: 'prepare'
# mode: 'train'
# mode: 'evaluate'
# mode: 'predict'


model:
  name: 'ResidualComplexNN'
  input_dim: 8 

#============#
# Data Block #
#============#
# Path to the data
data:
  signal_path: /scratch4/levans/tth-network/Datasets/basic/signal2.h5
  background_path: /scratch4/levans/tth-network/Datasets/basic/ttbarBackground2.h5

#===============#
# Network Block #
#===============#
Network_type:
  - FFNN


#===============#
# Feature Block #
#===============#
features:
  - HT_all
  - H0_all
  - dRbb_avg_Sort4
  - nJets
  - Aplanarity_jets
  - Centrality_all
  - dRlj_MindR
  - mu_pt

#===================#
# Preparation Block #
#===================#
# Preparation: Coming soon!


#================#
# Training Block #
#================#
training:
  num_epochs: 20           
  learning_rate: 0.00001   
  weight_decay: 0.001      
  batch_size: 100            
  patience: 7               
  early_stopping: True      
  use_scheduler: False      
  factor: 0.5               
  initialise_weights: True  
  balance_classes: True     
  criterion: 'BCELoss'      
  use_cosine_burnin: True   
  save_frequency: 1
  save_plots: False

#===================#
# Evaluataion Block #
#===================#
evaluation:
  use_saved_model: False
  saved_model_path: /scratch4/levans/tth-network/models/outputs/model.pt
