universe   = vanilla
executable = /afs/cern.ch/user/l/leevans/NNTrainer/tth-network/HTCondor/train_condor.sh
getenv     = True

Request_GPUs = 1
request_memory = 40 GB

output    = logs/$(ClusterId).$(ProcId).out
error     = logs/$(ClusterId).$(ProcId).err
log       = logs/$(ClusterId).log

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
+JobFlavour = "tomorrow"
+queue="short"

queue 1