# =============================================== #
# Residual Complex NN (nn4) Testing Configuration #
# =============================================== #

# --------------------------------------------------------------------------------------

#=============#
# Model Block #
#=============#
model:
  name: 'ResidualComplexNN'
  input_dim: 11

#============#
# Data Block #
#============#
data:
  signal_path: /scratch4/levans/tth-network/Datasets/full/10_03_24/ttH/ttH_AFII.h5
  background_path: /scratch4/levans/tth-network/Datasets/full/10_03_24/ttbb/ttbb_AFII.h5
  train_ratio: 0.8
  value_threshold: 1e-6
  plot_inputs: False
  plot_save_path: /scratch4/levans/tth-network/plots/

#===============#
# Network Block #
#===============#
Network_type:
  - FFNN

#===============#
# Feature Block #
#===============#
features:
  - dRbb_avg_Sort4
  - HT_all
  - met_met
  - mwt_mwt
  - H0_all
  - H1_all
  - H2_jets
  - dRlj_MindR
  - dRlepbb_MindR_70
  - Centrality_all
  - dEtabb_MaxdEta_70
  - L2_Reco_higgs_pt
  - L2_Class_ttH_discriminant # some fun :p

#===================#
# Preparation Block #
#===================#
preparation:
  feature_maker: False
  feature_type: '4-vectors'
  max_particles: 5
  n_leptons: 1
  append_four_vectors: False
  use_four_vectors: False

#================#
# Training Block #
#================#
training:
  num_epochs: 30
  learning_rate: 0.01
  weight_decay: 0.001
  batch_size: 512
  patience: 10
  early_stopping: True
  use_scheduler: True
  factor: 0.5
  initialise_weights: True
  balance_classes: True
  criterion: 'BCELoss'
  use_cosine_burnin: False
  lr_init: 1e-5
  lr_max: 1e-1
  lr_final: 1e-5
  burn_in: 3
  ramp_up: 5
  plateau: 15
  ramp_down: 17
  model_save_path: /scratch4/levans/tth-network/models/outputs/


#==================#
# Evaluation Block #
#==================#
evaluation:
  # save_frequency: 5
  #saved_model_path: /scratch4/levans/tth-network/models/outputs/model.pt
  use_saved_model: False
  plot_loss_landscape: False

# --------------------------------------------------------------------------------------